# Generated by Django 4.2.13 on 2024-07-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_is_active', 'может блокировать пользователей')]},
        ),
    ]
