# Generated by Django 4.2.13 on 2024-06-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sends', '0002_alter_client_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'сообщение для рассылки',
                'verbose_name_plural': 'сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рассылки')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала рассылки')),
                ('stop_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки')),
                ('frequency', models.CharField(choices=[('EVERY_DAY', 'Раз в день'), ('EVERY_WEEK', 'Раз в неделю'), ('EVERY_MONTH', 'Раз в месяц')], default='EVERY_DAY', max_length=200, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('FINISHED', 'Завершена'), ('STARTED', 'Запущена')], default='CREATED', max_length=200, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(blank=True, related_name='mailing_settings', to='email_sends.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_settings', to='email_sends.message', verbose_name='Сообщение для рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время последней попытки отправки')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка')], max_length=200, verbose_name='Статус отправки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_sends.mailingsettings', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
