# Generated by Django 4.2.13 on 2024-06-26 09:21

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('email_sends', '0003_message_mailingsettings_mailinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_at',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Дата и время начала рассылки'),
        ),
    ]
