# Generated by Django 4.2.13 on 2024-06-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sends', '0004_alter_mailingsettings_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_log', to='email_sends.mailingsettings', verbose_name='Рассылка'),
        ),
    ]
