# Generated by Django 4.2.13 on 2024-07-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sends', '0007_client_creator_message_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('can_change_status', 'может менять статус')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
